// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-quests.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-quests.ts
var list_quests_default = defineTool({
  name: "list_quests",
  title: "List published quests",
  description: "List published quests (photo adventures) with title, mode and creation date.",
  inputSchema: {
    mode: z.enum(["solo", "multiplayer", "treasure_hunt"]).optional().describe("Filter by quest mode."),
    search: z.string().trim().min(1).max(100).optional().describe("Case-insensitive title search."),
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum quests to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ mode, search, limit }) => {
    const supabase = supabaseAnon();
    let query = supabase.from("quests").select("id, title, description, mode, status, time_limit_sec, max_players, created_at").eq("status", "published").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (mode) query = query.eq("mode", mode);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { quests: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-quest.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_quest_default = defineTool2({
  name: "get_quest",
  title: "Get quest details",
  description: "Get a published quest with its public task hints (hidden scoring criteria are never returned).",
  inputSchema: { quest_id: z2.string().uuid().describe("ID of the quest.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ quest_id }) => {
    const supabase = supabaseAnon();
    const { data: quest, error } = await supabase.from("quests").select("id, title, description, mode, status, time_limit_sec, max_players, created_at").eq("id", quest_id).eq("status", "published").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!quest) {
      return { content: [{ type: "text", text: "No published quest with that id." }], isError: true };
    }
    const { data: tasks, error: tErr } = await supabase.from("quest_tasks_public").select("id, order_idx, title, description, max_points").eq("quest_id", quest_id).order("order_idx");
    if (tErr) return { content: [{ type: "text", text: tErr.message }], isError: true };
    const result = { ...quest, tasks: tasks ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-leaderboard.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var get_leaderboard_default = defineTool3({
  name: "get_quest_leaderboard",
  title: "Get quest leaderboard",
  description: "Get the public leaderboard (rank, nickname, score, duration) for a quest.",
  inputSchema: {
    quest_id: z3.string().uuid().describe("ID of the quest."),
    limit: z3.number().int().min(1).max(50).default(10).describe("How many entries to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ quest_id, limit }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("quest_leaderboard").select("rank, nickname, total_score, duration_sec, status, completed_at").eq("quest_id", quest_id).order("rank").limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "world-wanderer",
  title: "World Wanderer",
  version: "0.1.0",
  instructions: "Read-only tools for the World Wanderer photo-quest app. Use `list_quests` to browse published quests, `get_quest` for a quest and its public task hints, and `get_quest_leaderboard` for public rankings. Only public data is exposed \u2014 no player photos, accounts or private sessions.",
  tools: [list_quests_default, get_quest_default, get_leaderboard_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
